TASK_TYPE_CHOICES = [
        ('assign_team', 'Assign Team to Client'),
        ('create_proposal', 'Create Proposal'),
        ('approve_proposal', 'Approve Proposal'),
        ('schedule_brief_meeting', 'Schedule Brief Meeting'),
        ('create_strategy', 'Create Strategy'),
        ('content_writing', 'Content Writing'),
        ('approve_content_by_marketing_manager', 'Approve Content by Marketing Manager'),
        ('approve_content_by_account_manager', 'Approve Content by Account Manager'),
        ('creatives_design', 'Creatives Designing'),
        ('approve_creatives_by_marketing_manager', 'Approve Creatives by Marketing Manager'),
        ('approve_creatives_by_account_manager', 'Approve Creatives by Account Manager'),
        ('schedule_onboarding_meeting', 'Schedule Onboarding Meeting'),
        ('onboarding_meeting', 'Onboarding Meeting'),
        ('smo_scheduling', 'SMO & Scheduling'),
        ('invoice_submission', 'Invoice Submission'),
        ('payment_confirmation', 'Payment Confirmation'),
        ('monthly_report', 'Monthly Reporting'),
    ]