# Generated by Django 4.2.18 on 2025-08-18 11:44

from django.db import migrations, models
import pro_app.storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('plan', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('marketing_director', 'Marketing Director'), ('marketing_manager', 'Marketing Manager'), ('marketing_assistant', 'Marketing Assistant'), ('graphics_designer', 'Graphics Designer'), ('content_writer', 'Content Writer'), ('account_manager', 'Account Manager'), ('accountant', 'Accountant')], db_index=True, default='user', max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('agency_name', models.CharField(blank=True, max_length=255, null=True)),
                ('agency_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('acc_mngr_id', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('profile', models.FileField(blank=True, null=True, storage=pro_app.storage_backends.SupabaseStorage(), upload_to='profiles/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('plans', models.ManyToManyField(blank=True, related_name='assigned_account_managers', to='plan.plans')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
