# Generated by Django 4.2.18 on 2025-08-25 13:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('business_details', models.TextField(blank=True)),
                ('brand_key_points', models.TextField(blank=True)),
                ('business_address', models.CharField(max_length=255)),
                ('brand_guidelines_link', models.URLField(blank=True)),
                ('business_whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('goals_objectives', models.TextField(blank=True)),
                ('business_email_address', models.EmailField(max_length=254)),
                ('target_region', models.CharField(blank=True, max_length=255)),
                ('business_offerings', models.CharField(choices=[('services', 'Services'), ('products', 'Products'), ('services_products', 'Services Products'), ('other', 'Other')], default='services', max_length=20)),
                ('ugc_drive_link', models.URLField(blank=True)),
                ('business_website', models.URLField(blank=True)),
                ('social_handles', models.JSONField(blank=True, default=dict, help_text="Stores social handles as key-value pairs, e.g., {'facebook': 'https://facebook.com', 'instagram': 'https://instagram.com'}")),
                ('additional_notes', models.TextField(blank=True)),
                ('proposal_pdf', models.FileField(blank=True, null=True, upload_to='proposals/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('proposal_approval_status', models.CharField(blank=True, choices=[('approved', 'Approved'), ('declined', 'Declined'), ('changes_required', 'Changes Required')], max_length=20, null=True)),
                ('num_of_products', models.IntegerField(blank=True, null=True)),
                ('membership', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='none', max_length=4)),
                ('website_structure', models.TextField(blank=True, null=True)),
                ('design_preference', models.TextField(blank=True, null=True)),
                ('domain', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='none', max_length=4)),
                ('domain_info', models.CharField(blank=True, max_length=255, null=True)),
                ('hosting', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='none', max_length=4)),
                ('hosting_info', models.CharField(blank=True, max_length=255, null=True)),
                ('is_self_update', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='none', max_length=4)),
                ('client_type', models.CharField(choices=[('social_media', 'Social Media'), ('web_development', 'Web Development'), ('both', 'Both')], default='both', help_text='Indicates the type of service(s) selected by the client.', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clients', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='team.team')),
            ],
        ),
        migrations.CreateModel(
            name='ClientWorkflowState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.CharField(choices=[('assign_team', 'Assign Team to Client'), ('create_proposal', 'Create Proposal'), ('approve_proposal', 'Approve Proposal'), ('schedule_brief_meeting', 'Schedule Brief Meeting'), ('create_strategy', 'Create Strategy'), ('content_writing', 'Content Writing'), ('approve_content_by_marketing_manager', 'Approve Content by Marketing Manager'), ('approve_content_by_account_manager', 'Approve Content by Account Manager'), ('creatives_design', 'Creatives Designing'), ('approve_creatives_by_marketing_manager', 'Approve Creatives by Marketing Manager'), ('approve_creatives_by_account_manager', 'Approve Creatives by Account Manager'), ('schedule_onboarding_meeting', 'Schedule Onboarding Meeting'), ('onboarding_meeting', 'Onboarding Meeting'), ('smo_scheduling', 'SMO & Scheduling'), ('invoice_submission', 'Invoice Submission'), ('payment_confirmation', 'Payment Confirmation'), ('monthly_report', 'Monthly Reporting')], max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.clients')),
            ],
        ),
        migrations.CreateModel(
            name='ClientWebDevData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_type', models.CharField(choices=[('ecommerce', 'Ecommerce'), ('services', 'Services'), ('portfolio', 'Portfolio'), ('other', 'Other')], default='services', max_length=20)),
                ('num_of_products', models.IntegerField(blank=True, null=True)),
                ('membership', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('website_structure', models.TextField(blank=True, null=True)),
                ('design_preference', models.TextField(blank=True, null=True)),
                ('domain', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('domain_info', models.CharField(blank=True, max_length=255, null=True)),
                ('hosting', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('hosting_info', models.CharField(blank=True, max_length=255, null=True)),
                ('is_self_update', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webdev_data', to='client.clients')),
            ],
        ),
        migrations.CreateModel(
            name='ClientStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='In Progress', max_length=50)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.clients')),
            ],
        ),
        migrations.CreateModel(
            name='ClientsPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Attributes of the plan')),
                ('platforms', models.JSONField(blank=True, default=dict, help_text='Platforms like Facebook, Instagram')),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_plans', to='client.clients')),
            ],
        ),
        migrations.CreateModel(
            name='ClientInvoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_from', models.TextField(blank=True, null=True)),
                ('billing_to', models.TextField(blank=True, null=True)),
                ('invoice', models.FileField(blank=True, null=True, upload_to='invoices/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('submission_status', models.CharField(blank=True, choices=[('paid', 'PAID'), ('unpaid', 'UNPAID'), ('changes_required', 'CHANGES REQUIRED'), ('wait_for_approval', 'WAITING FOR APPROVAL')], default='wait_for_approval', max_length=20, null=True)),
                ('payment_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients_invoices', to='client.clients')),
            ],
        ),
    ]
