# Generated by Django 4.2.18 on 2025-08-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('attribute_type', models.CharField(choices=[('post_type', 'Post Type'), ('post_cta', 'Post CTA'), ('post_category', 'Post Category')], max_length=50)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
