# Generated by Django 4.2.18 on 2025-08-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postattribute',
            name='attribute_type',
            field=models.CharField(choices=[('post_type', 'Post Type'), ('post_cta', 'Post CTA'), ('post_category', 'Post Category')], db_index=True, max_length=20),
        ),
    ]
