# Generated by Django 4.2.18 on 2025-08-11 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(help_text='The title of the note.', max_length=255)),
                ('message', models.TextField(help_text='The message or content of the note.')),
                ('note_flag', models.BooleanField(default=False, help_text='Flag to indicate if the note is pinned or unpinned.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The timestamp when the note was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp when the note was last updated.')),
                ('sender', models.ForeignKey(blank=True, help_text='The user who created the note.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientMessageThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_threads', to='client.clients')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Message Thread',
                'verbose_name_plural': 'Client Message Threads',
                'ordering': ['-created_at'],
            },
        ),
    ]
