# Generated by Django 4.2.18 on 2025-08-25 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('assign_team', 'Assign Team to Client'), ('create_proposal', 'Create Proposal'), ('approve_proposal', 'Approve Proposal'), ('schedule_brief_meeting', 'Schedule Brief Meeting'), ('create_strategy', 'Create Strategy'), ('content_writing', 'Content Writing'), ('approve_content_by_marketing_manager', 'Approve Content by Marketing Manager'), ('approve_content_by_account_manager', 'Approve Content by Account Manager'), ('creatives_design', 'Creatives Designing'), ('approve_creatives_by_marketing_manager', 'Approve Creatives by Marketing Manager'), ('approve_creatives_by_account_manager', 'Approve Creatives by Account Manager'), ('schedule_onboarding_meeting', 'Schedule Onboarding Meeting'), ('onboarding_meeting', 'Onboarding Meeting'), ('smo_scheduling', 'SMO & Scheduling'), ('invoice_submission', 'Invoice Submission'), ('payment_confirmation', 'Payment Confirmation'), ('monthly_report', 'Monthly Reporting')], max_length=50)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='client.clients')),
            ],
        ),
        migrations.CreateModel(
            name='CustomTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.TextField()),
                ('task_description', models.TextField()),
                ('task_status', models.BooleanField(default=False)),
                ('task_created_at', models.DateTimeField(auto_now_add=True)),
                ('task_updated_at', models.DateTimeField(auto_now=True)),
                ('custom_task_file', models.FileField(blank=True, null=True, upload_to='task_files/')),
                ('assign_to_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_tasks', to='client.clients')),
            ],
        ),
    ]
