# Generated by Django 4.2.18 on 2025-08-25 13:42

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=255)),
                ('pricing_attributes', models.JSONField(blank=True, default=dict, help_text='Key-value pairs for attributes like reel:100, post:200, etc.')),
                ('pricing_platforms', models.JSONField(blank=True, default=dict, help_text='Key-value pairs for platforms like facebook:200, instagram:150, etc.')),
                ('standard_attributes', models.JSONField(blank=True, default=dict, help_text='Key-value pairs for attributes like reel:100, post:200, etc.')),
                ('standard_plan_inclusion', models.TextField(blank=True, help_text="Details of what's included in the standard plan", null=True)),
                ('standard_netprice', models.IntegerField(help_text='Net price for the standard plan')),
                ('advanced_attributes', models.JSONField(blank=True, default=dict, help_text='Key-value pairs for attributes like reel:100, post:200, etc.')),
                ('advanced_plan_inclusion', models.TextField(blank=True, help_text="Details of what's included in the advanced plan", null=True)),
                ('advanced_netprice', models.IntegerField(help_text='Net price for the advanced plan')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account_managers', models.ManyToManyField(blank=True, related_name='assigned_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
            },
        ),
    ]
