# Generated by Django 4.2.18 on 2025-08-25 13:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('month_name', models.CharField(db_index=True, max_length=20)),
                ('strategy_completed', models.BooleanField(default=False)),
                ('content_completed', models.BooleanField(default=False)),
                ('creatives_completed', models.BooleanField(default=False)),
                ('mm_content_completed', models.CharField(choices=[('waiting_for_approval', 'Waiting For Approval'), ('approve', 'Approve'), ('changes_required', 'Changes Required')], default='waiting_for_approval', help_text='Tracks the approval status of the content by marketing manager.', max_length=20)),
                ('acc_creative_completed', models.CharField(choices=[('waiting_for_approval', 'Waiting For Approval'), ('approve', 'Approve'), ('changes_required', 'Changes Required')], default='waiting_for_approval', help_text='Tracks the approval status of the creatives by account manager.', max_length=20)),
                ('mm_creative_completed', models.CharField(choices=[('waiting_for_approval', 'Waiting For Approval'), ('approve', 'Approve'), ('changes_required', 'Changes Required')], default='waiting_for_approval', help_text='Tracks the approval status of the creatives by marketing manager.', max_length=20)),
                ('acc_content_completed', models.CharField(choices=[('waiting_for_approval', 'Waiting For Approval'), ('approve', 'Approve'), ('changes_required', 'Changes Required')], default='waiting_for_approval', help_text='Tracks the approval status of the content by account manager.', max_length=20)),
                ('smo_completed', models.BooleanField(default=False, help_text='Indicates if the SMO task is completed for the month.')),
                ('monthly_reports', models.FileField(blank=True, null=True, upload_to='reports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='client.clients')),
            ],
        ),
        migrations.CreateModel(
            name='ClientCalendarDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('date', models.DateField()),
                ('post_count', models.IntegerField(default=0)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('cta', models.CharField(blank=True, max_length=255, null=True, verbose_name='Call to Action')),
                ('resource', models.TextField(blank=True, help_text='Strategy description for this post date', null=True)),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('hashtags', models.TextField(blank=True, help_text='Use commas to separate hashtags', null=True)),
                ('e_hooks', models.TextField(blank=True, null=True, verbose_name='Engagement Hooks')),
                ('creatives_text', models.TextField(blank=True, help_text='Describe the creatives text', null=True)),
                ('creatives', models.JSONField(blank=True, default=list, help_text='List of supabase URLs for multiple creatives (images/videos).')),
                ('internal_status', models.JSONField(blank=True, default=dict)),
                ('client_approval', models.JSONField(blank=True, default=dict)),
                ('comments', models.TextField(blank=True, null=True)),
                ('collaboration', models.TextField(blank=True, null=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='calender.clientcalendar')),
            ],
            options={
                'verbose_name': 'Client Calendar Date',
                'verbose_name_plural': 'Client Calendar Dates',
            },
        ),
    ]
